namespace: toucantoco

name: toucantoco

version: 0.4.2

readme: README.md

authors:
- ToucanToco Infra <infra@toucantoco.com>

description: ToucanToco custom Ansible collection

license:
- GPL-2.0-or-later

dependencies: {}

repository: https://github.com/ToucanToco/ansible-collection

build_ignore:
  - .ansible-venv*
  - scripts
  - .pytest_cache
  - .gitignore
  - Jenkinsfile
  - build
  - tests
  - docs
